services:
  shelly-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/simonjur/shelly-plug-s-g3-prometheus-exporter/shelly-plug-s-gen3-exporter:latest
    environment:
      LISTEN_PORT: 9769
    ports:
      - 10777:10777
    container_name: shelly-exporter
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config/config.yaml:ro
